[app]
TEST_MODE = true
DATABASE = "eventguard.db"

[gmail]
USER = "aishuaishwaryacg@gmail.com"
APP_PASSWORD = "dfpp jznm qqbg aabb"

[gemini]
API_KEY = "AIzaSyBRirQVwFTAYjSV6fi169-C4jIPFA7MrCQ"

[google]
MAPS_API_KEY = ""
